### ISSUE TITLE
Add images for "recent work"

### ISSUE THREAD

**Issue by alecho** [SimplyBinary/simplybinary.github.io#10]
@simplyb The designer didn't provide the images for "Recent Work" can you?

Copy is also needed.

**Comment by simplyb** [comment]
I've added to dropbox(barbri.png, capturelife.png, kona.png), images should be 200px x 135px.

**Comment by simplyb** [comment]
CaptureLife image isn't showing up.

**Comment by alecho** [comment]
I missed that the "L" was uppercase in the file name. Of course, it worked locally.

**Comment by simplyb** [comment]
Good times!
