### ISSUE TITLE
Recent Work copy

### ISSUE THREAD

**Issue by alecho** [SimplyBinary/simplybinary.github.io#18]
@simplyb Currently the recent work section uses filler text. Do we have that copy somewhere so I don't have to type it over again?

**Comment by simplyb** [comment]
CaptureLife - Re-imagining how you organize, collect, and browse all your photos in one place so you can easily capture, discover, and relive life.  Currently responsible for operations and development from the desktop to the web in javascript, go, objective-c, and c#.

Kona - Social collaboration for projects and teams.  A virtual equivalent to an open office environment for any organization to connect, stay organized, and be productive.  We were hired for our extensive knowledge of ruby and worked on the project from first commit to years after launching.

Barbri Law Preview - Training for the nation's top law students.  Helping you to organize, prepare, and conquer law school and exams.  Currently responsible for supporting both back-end and front-end development in PHP and Javascript.
